# Generated by Django 2.2.6 on 2020-02-20 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POST', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic_comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comments'),
        ),
        migrations.AddField(
            model_name='pic',
            name='pic_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POST.Post'),
        ),
    ]
