# Generated by Django 3.0.2 on 2020-02-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('POST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic_comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comments'),
        ),
        migrations.AddField(
            model_name='pic',
            name='pic_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POST.Post'),
        ),
    ]
