# Generated by Django 3.0.2 on 2020-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0002_auto_20200218_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='image',
            field=models.ImageField(upload_to='media/photos/users'),
        ),
    ]
