# Generated by Django 3.0.2 on 2020-02-19 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0003_auto_20200218_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='pic_comment_id',
        ),
    ]
