# Generated by Django 3.0.2 on 2020-02-20 09:23

import POST.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0004_remove_pic_pic_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='image',
            field=models.ImageField(upload_to=POST.models.user_pic_directory_path),
        ),
    ]
