# Generated by Django 3.0.2 on 2020-02-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0005_auto_20200220_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='pic_post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='vid_post_id',
            new_name='post',
        ),
    ]
